language: java
notifications:
  email: false
jdk:
- openjdk11
stages:
- install
jobs:
  include:
  - stage: install
    script:
    - mvn --settings=.maven.settings.xml clean install -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
